# Processing raw files

In [10]:
from regime_identification.Data.yf_tickers import load

import pandas as pd
import numpy as np
from datetime import datetime
import os
import yfinance as yf

## .tsv files from [BOLS](https://www.bls.gov/cpi/data.htm)

In [2]:
def process_bols(filename):
    df = pd.read_csv(filename, index_col = None, sep = "\t", 
                     header = None, names = ["ID", "Year", "Month", "Price", "Missing"], 
                     na_values = ["           -"])
    df = df.iloc[:, 1:4] # .dropna(how = "any")
    df["Price"] = df["Price"].astype(float).interpolate() # Fill missing prices with avgs
    df["Month"] = pd.Series([i[1:] for i in df["Month"]]).astype(int)
    # Loop over one month, because this data is only available at the first of the next month
    # df["Month"] = (df["Month"] % 12) + 1
    ## Note: Instead of this, just forward-fill the data. Same result.
    df["Day"] = 1
    df.index = pd.to_datetime(df.loc[:, ["Year", "Month", "Day"]])
    df.index.name = "Date"

    return df["Price"]

bols_df = pd.DataFrame()
for i in os.listdir():
    if not i.endswith(".tsv"): continue
        
    name = i[:-4]
    bols_df[name] = process_bols(i)

bols_df.tail(40)

,electricity_kwh,gasoline_gallon,household-gas_therm,housing,inflation_cpi
Date,,,,,
2023-04-01,0.1650,3.839,1.413,317.366,302.845
2023-05-01,0.1650,3.794,1.385,318.146,303.334
2023-06-01,0.1700,3.821,1.371,319.355,304.014
2023-07-01,0.1690,3.842,1.395,320.552,304.609
2023-08-01,0.1700,4.064,1.402,321.520,306.082
2023-09-01,0.1710,4.107,1.377,323.250,307.276
2023-10-01,0.1690,3.910,1.388,324.251,307.696
2023-11-01,0.1680,3.623,1.442,325.495,308.148
2023-12-01,0.1690,3.411,1.429,326.520,308.741
2024-01-01,0.1730,3.353,1.452,328.419,309.698
2024-02-01,0.1730,3.486,1.465,329.687,310.967
2024-03-01,0.1740,3.707,1.429,331.054,312.345
2024-04-01,0.1730,3.907,1.375,331.697,313.023
2024-05-01,0.1750,3.885,1.369,332.638,313.175
2024-06-01,0.1780,3.729,1.407,333.368,313.044
2024-07-01,0.1780,3.747,1.408,334.461,313.569
2024-08-01,0.1770,3.648,1.401,335.483,314.062
2024-09-01,0.1780,3.478,1.399,336.436,314.732
2024-10-01,0.1770,3.412,1.422,337.826,315.631
2024-11-01,0.1760,3.315,1.487,338.952,316.528
2024-12-01,0.1760,3.277,1.522,339.905,317.604
2025-01-01,0.1790,3.342,1.552,341.068,318.961
2025-02-01,0.1790,3.396,1.584,342.357,319.679
2025-03-01,0.1810,3.368,1.596,343.327,319.785
2025-04-01,0.1810,3.465,1.626,344.850,320.302
2025-05-01,0.1820,3.443,1.626,345.845,320.620
2025-06-01,0.1900,3.442,1.653,346.893,321.435
2025-07-01,0.1890,3.422,1.642,347.642,322.169
2025-08-01,0.1900,3.433,1.634,348.822,323.291
2025-09-01,0.1880,3.481,1.613,349.429,324.245
2025-10-01,0.1885,3.427,1.626,350.141,324.654
2025-11-01,0.1890,3.373,1.639,350.853,325.063
2025-12-01,0.1890,3.195,1.701,352.085,326.031
2026-01-01,0.1920,3.104,1.704,352.739,326.588
2026-02-01,0.1890,3.211,1.749,353.699,327.460
2026-03-01,0.1900,3.988,1.688,354.888,330.293
2026-04-01,0.1940,4.409,1.676,357.366,332.407
2026-05-01,0.1960,4.793,1.677,358.244,333.979
2026-06-01,0.1980,4.346,1.688,358.413,332.568
2026-07-01,0.1970,4.242,1.704,358.931,332.813

In [3]:
# saving
bols_df.to_csv("bols.csv")

## 3M-10Y Treasury Yield Curve

In [6]:
t_yields = pd.DataFrame()
t_files = ["treasury_yield_3mo.csv", "treasury_yield_10y.csv"]
for filename in t_files:
    df = pd.read_csv(filename, index_col = 0, 
                     header = 0, names = ["Date", "Price"], 
                    )
    name = filename[:-4]
    t_yields[name] = df

# Yield curve
t_yields["treasury_yield_curve"] = t_yields["treasury_yield_3mo"] / t_yields["treasury_yield_10y"]

t_yields.to_csv("treasury_yields.csv")

In [7]:
t_yields

            treasury_yield_3mo  treasury_yield_10y  treasury_yield_curve
Date
1981-09-01               17.01               15.41              1.103829
1981-09-02               16.65               15.40              1.081169
1981-09-03               16.96               15.48              1.095607
1981-09-04               16.64               15.51              1.072856
1981-09-07                 NaN                 NaN                   NaN
...                        ...                 ...                   ...
2026-08-26                3.85                4.66              0.826180
2026-08-27                3.84                4.67              0.822270
2026-08-28                3.90                4.73              0.824524
2026-08-31                3.91                4.75              0.823158
2026-09-01                3.92                4.79              0.818372

[11741 rows x 3 columns]

## Foreign Exchange

In [8]:
fx_df = pd.DataFrame()
fx_files = ["fx_JPUS.csv", "fx_USEU.csv", "fx_USUK.csv"]
for filename in fx_files:
    df = pd.read_csv(filename, index_col = 0, 
                     header = 0, names = ["Date", "Price"], 
                    )
    name = filename[:-4]
    fx_df[name] = df

fx_df.to_csv("fx_rates.csv")

## Gold

In [28]:
gold = pd.read_csv("gold_historical.csv", index_col = 0, names = ["Date", "gold", "Source"])
gold = gold.drop("Source", axis = 1).iloc[1:, :]
gold = gold[~gold.index.duplicated(keep = "first")]

In [29]:
gold.to_csv("gold.csv")

## VIX

In [16]:
vix = yf.Ticker("^VIX").history(period = "50y")
vix = pd.DataFrame(vix["Close"], index = vix.index)
vix.columns = ["VIX"]

In [24]:
vix.to_csv("VIX.csv")

# Assembly

In [25]:
polished_csvs = [ 
    "bols.csv", "interest_rates.csv", 
    "sp500_avg-pe-ratio.csv", "treasury_yields.csv",
    "US_GDP.csv", "fx_rates.csv",
    "gold.csv", "VIX.csv"
]

dfl = []
for i in polished_csvs:
    dfl.append(load(i))

final = pd.concat(dfl, axis = 1, join = "outer", ignore_index = False, sort = True)

final.to_csv("extramarket.csv")
final

,electricity_kwh,gasoline_gallon,household-gas_therm,housing,inflation_cpi,BLP,FF,pe_ratio,treasury_yield_3mo,treasury_yield_10y,treasury_yield_curve,GDP,fx_JPUS,fx_USEU,fx_USUK,gold,VIX
Date,,,,,,,,,,,,,,,,,
1258-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
1259-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
1260-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
1261-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
1262-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.89,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2026-09-07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.300000
2026-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.720000
2026-09-09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16.459999
2026-09-10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,17.840000
2026-09-11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.840000

In [27]:
final.index.has_duplicates

False